package com.rakshak.security.utils;

import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.Context;
import android.graphics.Color;

import androidx.core.app.NotificationCompat;

import com.rakshak.security.core.RiskResult;

/**
 * Centralized notification utility for Rakshak.
 *
 * SECURITY NOTE:
 * - Used only for user-visible warnings
 * - No background abuse
 * - No silent notifications
 */
public final class NotificationUtil {

    private static final String CHANNEL_ID = "rakshak_security_alerts";
    private static final String CHANNEL_NAME = "Rakshak Security Alerts";

    // Prevent instantiation
    private NotificationUtil() {}

    // =================================================
    // PUBLIC API
    // =================================================

    /**
     * Shows a warning notification for suspicious SMS messages.
     */
    public static void showSmsWarning(
            Context context,
            String sender,
            RiskResult result
    ) {
        String title = "⚠ Suspicious SMS Detected";
        String subtitle = (sender != null && !sender.isEmpty())
                ? "From: " + sender
                : "Unknown sender";

        showNotification(context, title, subtitle, result);
    }

    // =================================================
    // CORE NOTIFICATION LOGIC
    // =================================================

    private static void showNotification(
            Context context,
            String title,
            String subtitle,
            RiskResult result
    ) {

        NotificationManager manager =
                (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);

        if (manager == null || result == null) return;

        // Create notification channel (safe to call multiple times)
        NotificationChannel channel =
                new NotificationChannel(
                        CHANNEL_ID,
                        CHANNEL_NAME,
                        NotificationManager.IMPORTANCE_HIGH
                );

        channel.setDescription("Security warnings generated by Rakshak");
        channel.enableLights(true);
        channel.enableVibration(true);
        channel.setLightColor(getRiskColor(result.level));

        manager.createNotificationChannel(channel);

        NotificationCompat.Builder builder =
                new NotificationCompat.Builder(context, CHANNEL_ID)
                        .setSmallIcon(android.R.drawable.stat_notify_error)
                        .setContentTitle(title)
                        .setContentText(subtitle)
                        .setStyle(
                                new NotificationCompat.BigTextStyle()
                                        .bigText(result.getExplanationText())
                        )
                        .setPriority(NotificationCompat.PRIORITY_HIGH)
                        .setAutoCancel(true)
                        .setColor(getRiskColor(result.level));

        manager.notify(generateNotificationId(), builder.build());
    }

    // =================================================
    // HELPERS
    // =================================================

    private static int generateNotificationId() {
        return (int) (System.currentTimeMillis() & 0xFFFFFFF);
    }

    private static int getRiskColor(RiskResult.RiskLevel level) {
        switch (level) {
            case HIGH:
                return Color.RED;
            case MEDIUM:
                return Color.rgb(255, 165, 0); // Orange
            case LOW:
            default:
                return Color.GREEN;
        }
    }
}
